### ISSUE TITLE
Pull this repo back into pulumi-hugo

### ISSUE THREAD

**Issue by cnunciato** [pulumi/theme#105]
The job of this repo is to build the CSS and JS bundles we use on the website. In this repo today, when a change is made to one of these source files and committed to `master`, a GitHub Actions job runs that compiles all CSS and JS source files into a set of non-minified bundles and writes them to the `assets` folder, which it then commits back to `master` and then merges into `release`. This allows other Hugo modules -- pulumi/docs, pulumi/registry, pulumi/pulumi-hugo -- to consume these bundles using `hugo mod get` in the usual way:

```
hugo mod get github.com/pulumi/theme@release
```

We get many benefits from storing these compiled, not-yet-minified bundles in the `assets` folder like this, but the biggest is that by doing so, we're able to make them available to any Hugo project that needs them as part of the Hugo [virtual filesystem](https://gohugo.io/hugo-modules/). When `hugo` runs (whether in `serve` or `build` mode), it assembles this filesystem by merging all member-module folders (static, content, layouts, data, assets, etc.) into a single list (according to the precedence rules we specify in config.yaml), which makes `assets/js/bundle.js` and `assets/css/bundle.css` available at the correct site-root-relative location. This makes local development super-fast for those users (most of them) who don't need to make changes to CSS and JS files (as the bundles are already there and ready to use). Front-end devs who do need to make such changes, though, can run `make serve` in this repo alongside the `make serve` they run in pulumi-hugo, which, when pointed at `../theme` (e.g., using a [`go.mod` `replace`](https://gohugo.io/hugo-modules/use-modules/#make-and-test-changes-in-a-module) or [`HUGO_MODULE_REPLACEMENTS` environment variable](https://gohugo.io/hugo-modules/configuration)), will hot-reload any changes to CSS or JS source files because Webpack and Stencil compile into `../theme/assets` -- which the `hugo` process automatically watches for changes by virtue of its belonging to the virtual filesystem. It all works pretty nicely, IMO -- but it's also something you have to understand, know how to work with, etc., which can be a bit of a pain.

So if we wanted to simplify things a bit, we _could_ pull all of this stuff into pulumi-hugo instead, and wire things up such that we'd end up with the same `assets` folder we have in this repo today (along with a release branch, so we don't end up shipping someone's local dev build by accident) in pulumi-hugo, and doing so shouldn't be too big an undertaking. Here are the steps I think we'd need to take in order to do that:

* Add all of the files and folders in this repo to pulumi-hugo (except the repo-specific ones, like `.github`, `go.mod`, `Makefile`, `README`)
* Add a new Make target (e.g., `make serve-assets`) to pulumi-hugo to do what `make serve` does in this repo today: https://github.com/pulumi/theme/blob/d59eb7712459e5da203c8011cfff4880bd961031/package.json#L34. Alternatively, we could use something like `concurrently` to run both `hugo` and the front-end dev servers as children of the same process, but I'd personally argue against this, as it'd complicate and weigh down the local-dev process for the 99% of users who just want to write a blog post or make a few docs changes
* Update `make ensure` to install all the new stuff as well
* Add a new `release` branch to pulumi-hugo (from `master` of course)
* Update the `push` workflow in pulumi-hugo to build CSS and JS assets and commit them back to `pulumi-hugo@master` and `@release` as we do here: https://github.com/pulumi/theme/blob/d59eb7712459e5da203c8011cfff4880bd961031/.github/workflows/push.yml#L21-L39    
* Update the registry and docs repos to consume the release branch of pulumi-hugo going forward

I _think_ that's it -- I might be overlooking something (commit histories always make this sort of thing more complicated), but I'm pretty sure that'd just about cover it, and it'd likely only be a size-medium sort of undertaking.

All this said, I'm still not convinced we _should_ do this; I personally think what we have is pretty flexible, and I like having these assets managed in one place like this, but again, I do recognize it's a bit of a pain for some. It's worth pointing out, though, that if we did decide get rid of this module, changes to other modules like registry and others that require accompanying CSS or JS changes would still require the same workflow: run `make serve-assets` in pulumi-hugo, point your registry branch to that, push branches for both, PR carefully, etc. So I'm not sure how big a win it'd actually be in practice. But it's possible nonetheless. Hope it helps!

**Comment by susanev** [comment]
thanks @cnunciato!! @kimberleyamackenzie feel free to add this to ur epic if you'd like to.
