### ISSUE TITLE
Minor docs nav issues

### ISSUE THREAD

**Issue by cnunciato** [pulumi/theme#107]
Noticed a couple of little things with the nav that it seemed worth filing for.

In Registry, if you open the drop-down menu, you can click outside the menu to close it. This behavior doesn't seem to have been applied to the Docs nav yet, though; clicking outside that nav seems to have no effect.

Also, when you scroll with the nav menu open, and the nav is replaced with the sticky version, the menu stays in the page:

![image](https://user-images.githubusercontent.com/274700/163251343-b39741cd-b286-470e-b5e0-2198126be048.png)

It's the same in Registry, but less noticeable, as the currently nav scrolls out of view.

Lastly, in the sticky menu, the Pulumi logo doesn't seem to be interactive. Should it open a menu as well? Take you back to the Docs page, or maybe the Pulumi home page?

**Comment by susanev** [comment]
added to the current milestone, as we currently have some things planned for this iteration in this area. its lower priority than a few things, but hoping we are able to get to it. thx for the report!

**Comment by kimberleyamackenzie** [comment]
- [ ] Handle select outside menu to close in docs
- [ ] Close nav when scrolling (because sticky nav covers it) in docs
- [ ] Close nav when scrolling (because sticky nav covers it) in registry
