### ISSUE TITLE
Move docs Sentry slack notifications 

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/theme#146]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Right now, Sentry slack notifications for docs go to the service team's notifications channel.  These aren't actionable for the service team, so they should post in a different channel for visibility with the right folks - maybe #website-notifications.

**Comment by susanev** [comment]
i think this is done, pls reopen if im wrong
