### ISSUE TITLE
Links without trailing slash causing thousands of minor SEO errors.

### ISSUE THREAD

**Issue by Brant-Soler** [pulumi/theme#67]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Google is seeing thousands of 301 redirects which have persisted over time. We're expected to correct these soft errors when we make changes but the Google gives us plenty of time to do so. Upon crawling the site, each of these links resolves as a 301, doubling the size of the website and flagging half of it as an error. 

Is there a way to bulk append a trailing slash to these links? Do you have any other ideas for correcting this? Totally open to ideas.

### Steps to reproduce

Visit [this page in the Registry](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/), scroll about halfway down to the Functions section, and hold your mouse over a link (MacOs + Chrome) to preview the address in the lower-left corner.

You should see an address like in this attached image.
![Screen Shot 2022-02-22 at 11 57 54 AM](https://user-images.githubusercontent.com/99282439/155213770-c4e4923f-1382-4ce7-a10d-3663464412ae.png)

**Comment by Brant-Soler** [comment]
Thank you for your responses, yes, please assist with the fix, it is outside of my wheelhouse.

**Comment by Brant-Soler** [comment]
As a post-mortem, this solution successfully resolved all 15,000 errors. Thank you @susanev and @kimberleyamackenzie.

**Comment by susanev** [comment]
what solution?

**Comment by Brant-Soler** [comment]
It looks like this fix was lost somehow in the pricing page update. @kimberleyamackenzie would you please replace the regex and slip it in the cue?

**Comment by Brant-Soler** [comment]
When this fix is implemented on Monday, can you also apply trailing slashes to all the resources?

![Screen Shot 2022-03-04 at 8 08 57 AM](https://user-images.githubusercontent.com/99282439/156800308-17b4060b-9555-4c3a-8d46-f9eec55e76c3.png)

**Comment by susanev** [comment]
we are not implementing this fix on monday. we are planning for the iteration monday, and will let you know if this makes it into the iteration. if so, it will happen sometime in the next 3 weeks.

if you would like to report this issue on the resources page pls open it in pulumi-hugo, that is something @cnunciato or @zchase may be able to help you with.

**Comment by Brant-Soler** [comment]
@zchase or @cnunciato can you spare a moment of time to add a pair of trailing slashes to the template identified by Kimberley above and shown in the screenshot two messages above? Quick, easy fix with a big gain.

**Comment by susanev** [comment]
@Brant-Soler the user experience team will take the work in the theme repo where this issue is. pls open a new issue for the work you want Christian and Zack to do.
