### ISSUE TITLE
Track data for new docs search experience

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/theme#98]
In the updated docs search experience, we're moving the get started button.  Currently, the get started button is on the right side of the header, which is always visible (pinned when scrolling).  In the new experience, when the header is visible, the get started button will be in the practitioner nav on the left.  When scrolling, the search bar will be pinned, and the get started button will remain on the left. 

### Search not pinned
<img width="1183" alt="Screen Shot 2022-04-06 at 10 10 12 AM" src="https://user-images.githubusercontent.com/25756367/162085391-4953c8e9-4467-44cd-9d68-c5ac4ebb0df0.png">

### Search pinned
<img width="978" alt="Screen Shot 2022-04-06 at 10 09 23 AM" src="https://user-images.githubusercontent.com/25756367/162085443-779e1fc9-dfe5-4d28-91ab-bb3fbe037a0a.png">

We want to observe the data to ensure that we don't see a decrease of relevant metrics due to this change.  For all the below queries, date ranges will need updating. 

[This Google Analytics query tracks usage of the get started button in the header from any docs page](https://analytics.google.com/analytics/web/#/report/content-event-events/a116166038w172505890p172019141/_u.date00=20220201&_u.date01=20220228&_r.drilldown=analytics.eventCategory:User%20Interaction,analytics.eventAction:link-click&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22header-get-started%22,0%5D,%5B0,%22analytics.eventLabel%22,%22PT%22,%22docs%22,0%5D%5D&explorer-graphOptions.selected=analytics.nthMonth/)

[This Google analytics query that tracks usage of the new get started button on the docs pinned search](https://analytics.google.com/analytics/web/#/report/content-event-events/a116166038w172505890p172019141/_u.date00=20220406&_u.date01=20220406&_r.drilldown=analytics.eventCategory:User%20Interaction,analytics.eventAction:link-click&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22get-started-pinned-search%22,0%5D%5D&explorer-graphOptions.selected=analytics.nthMonth/) and[ this query tracks use of the get started button on the practitioner nav.](https://analytics.google.com/analytics/web/#/report/content-event-events/a116166038w172505890p172019141/_u.date00=20220405&_u.date01=20220408&_r.drilldown=analytics.eventCategory:User%20Interaction,analytics.eventAction:link-click&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22get-started-practitioner-nav%22,0%5D%5D&explorer-graphOptions.selected=analytics.nthMonth/)

Spreadsheet where I'm tracking the data screenshotted below: https://docs.google.com/spreadsheets/d/1C0wuyOJBFcLdY3iGGxZglg0H2tcKXnC_hq_ciLeRR70/edit#gid=0

FYI @meagancojocar @zchase @susanev .

Related PRs: https://github.com/pulumi/pulumi-hugo/pull/1243 and https://github.com/pulumi/pulumi-hugo/pull/1243

**Comment by lukehoban** [comment]
Might also be interesting to look at a few other metrics related to this change:
1. How much search box interaction are we getting?  Hopefully more! But I can also plausibly imagine the new UX actually could plausibly decrease engagement because of search being outside the core content window container.
2. Are we impacting traffic out from /docs/* into key pages like /pricing, /blog and /learn?

**Comment by susanev** [comment]
@kimberleyamackenzie lets plan to review the data on fridays every day this month and post updates here on the issue.

**Comment by kimberleyamackenzie** [comment]
@susanev Yeah, totally.  I'm putting a 15 min time block on my own calendar for that, let's connect in the UX team meeting tomorrow to decide who else should get invited or if it should be async.

@lukehoban 
1. Great, the swiftype app does this tracking for us.  I don't think we have a way to breakdown between registry and docs in there, since they share an engine, but I'll investigate more.  And even without breaking it down, the metric should still be helpful to us, as long as no other big changes happen in registry/docs in the monitoring period.
2.  I _think_ [this query](https://metabase.corp.pulumi.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzcsImZpbHRlciI6WyJhbmQiLFsiY29udGFpbnMiLFsiZmllbGQiLDM5MyxudWxsXSwicHVsdW1pLmNvbS9kb2NzLyIseyJjYXNlLXNlbnNpdGl2ZSI6ZmFsc2V9XSxbImRvZXMtbm90LWNvbnRhaW4iLFsiZmllbGQiLDM4NSxudWxsXSwiZG9jcyIseyJjYXNlLXNlbnNpdGl2ZSI6ZmFsc2V9XV0sImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiwzODUsbnVsbF1dfSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=) should work for analyzing if traffic from docs -> not docs is impacted.  

I'll include both in the ones we monitor.

**Comment by susanev** [comment]
ah @kimberleyamackenzie i was thinking async. i actually have to miss our team meeting tomorrow for another meeting. but we can catch up in our 1-1 tomorrow.

**Comment by kimberleyamackenzie** [comment]
Data update for this week - we released Tuesday, so I'm going to compare to last Tuesday - Fri.  Obviously a small sample size, so not super scientific, but it looks like use of the get started button + traffic from docs to non-docs page is stable, and use of search has increased 30%! :tada:

<img width="605" alt="Screen Shot 2022-04-08 at 1 23 42 PM" src="https://user-images.githubusercontent.com/25756367/162525090-a29cb32e-ee0c-41c7-ac84-5aa6a3d06ee7.png">

**Comment by kimberleyamackenzie** [comment]
### Update for this week

Increased the period we're looking at to compare 10 total days of data (from release to yesterday for the new experience, and the 10 days before release for the old experience).  Looks like about a ~7% decrease in use of the get started button, stable traffic from docs -> non-docs pages, and an increase in use of search of around 12%.

<img width="587" alt="Screen Shot 2022-04-15 at 9 52 22 AM" src="https://user-images.githubusercontent.com/25756367/163598788-0d919d9a-8646-4a4d-8991-4fd45bfd53aa.png">

**Comment by kimberleyamackenzie** [comment]
## Update for this week

We're now looking a total of 16 days of data, and the new experience shows some definite lag for the docs -> non-docs traffic and a little bit for the get started button.  Search is still ahead with the new experience, though not by as much as we initially saw - curious if that has something to do with the low click through metrics we have been seeing in search.

<img width="575" alt="Screen Shot 2022-04-22 at 11 48 14 AM" src="https://user-images.githubusercontent.com/25756367/164776779-88f35cd0-60aa-4ce0-81a6-a00b4d4e169b.png">

**Comment by susanev** [comment]
@kimberleyamackenzie can you pull numbers specifically for the pricing page, so how many folks are going from docs to pricing page now vs back then?

**Comment by kimberleyamackenzie** [comment]
[3/15 - 3/31](https://metabase.corp.pulumi.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzcsImZpbHRlciI6WyJhbmQiLFsiY29udGFpbnMiLFsiZmllbGQiLDM5MyxudWxsXSwicHVsdW1pLmNvbS9kb2NzLyIseyJjYXNlLXNlbnNpdGl2ZSI6ZmFsc2V9XSxbImNvbnRhaW5zIixbImZpZWxkIiwzODUsbnVsbF0sInByaWNpbmciLHsiY2FzZS1zZW5zaXRpdmUiOmZhbHNlfV0sWyI-IixbImZpZWxkIiwzOTcsbnVsbF0sIjIwMjItMDMtMTQiXSxbIjwiLFsiZmllbGQiLDM5NyxudWxsXSwiMjAyMi0wNC0wMSJdXSwiYWdncmVnYXRpb24iOltbImNvdW50Il1dfSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5Ijoic2NhbGFyIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319): 632
[4/5 - 4/21](https://metabase.corp.pulumi.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjM3LCJmaWx0ZXIiOlsiYW5kIixbImNvbnRhaW5zIixbImZpZWxkIiwzOTMsbnVsbF0sInB1bHVtaS5jb20vZG9jcy8iLHsiY2FzZS1zZW5zaXRpdmUiOmZhbHNlfV0sWyJjb250YWlucyIsWyJmaWVsZCIsMzg1LG51bGxdLCJwcmljaW5nIix7ImNhc2Utc2Vuc2l0aXZlIjpmYWxzZX1dLFsiPiIsWyJmaWVsZCIsMzk3LG51bGxdLCIyMDIyLTA0LTA0Il0sWyI8IixbImZpZWxkIiwzOTcsbnVsbF0sIjIwMjItMDQtMjIiXV0sImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5Ijoic2NhbGFyIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319): 267

**Comment by susanev** [comment]
@lukehoban would be good to get your thoughts and feelings on ⬆️ and if you want us to make changes because of it.

**Comment by kimberleyamackenzie** [comment]
Ran these numbers again today, since it has been a full 3 weeks of data.  Data points below.  I will be out on PTO for a bit, so I have linked the exact queries I'm using for each number [in the spreadsheet ](https://docs.google.com/spreadsheets/d/1C0wuyOJBFcLdY3iGGxZglg0H2tcKXnC_hq_ciLeRR70/edit#gid=0) in case folks want to run for different dates.

<img width="627" alt="Screen Shot 2022-04-27 at 12 59 23 PM" src="https://user-images.githubusercontent.com/25756367/165621134-0bdb3d9c-a473-49de-89be-214e622c5ada.png">

**Comment by kimberleyamackenzie** [comment]
I did one last look here now that I'm back from PTO, [looking at a total of 38 days of data](https://docs.google.com/spreadsheets/d/1C0wuyOJBFcLdY3iGGxZglg0H2tcKXnC_hq_ciLeRR70/edit#gid=0).  Things are pretty on the first two comparison points, searches with the new experience are still up + traffic from docs -> pricing is still significantly lower with the new experience.

<img width="529" alt="Screen Shot 2022-05-16 at 11 17 32 AM" src="https://user-images.githubusercontent.com/25756367/168657182-d6efa084-2dd7-48a4-a6bb-784f0c7fa89c.png">

We should decide if we want to use this data to make any changes or follow-up issues to this experience - what do you think @meagancojocar @susanev?
